config/routes.rb
Rails.application.routes.draw do
  resources :charts
  devise_for :users
  resources :categories
  resources :money_transactions
  resources :notes
  resources :people
  get "homepage", to: "home#homepage"
  root "people#index"
end

app/controllers/money_transactions_controller.rb
# frozen_string_literal: true

class MoneyTransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]
  before_action :set_person_category, only: [:destroy]
  before_action :set_person_created_for, only: %i[create update]

  # GET /money_transactions or /money_transactions.json
  def index
    @transactions = MoneyTransaction.all
  end

  # GET /money_transactions/1 or /money_transactions/1.json
  def show
    @person = Person.find(PersonCategory.find(@transaction.person_category_id).id)
    @category = Category.find(PersonCategory.find(@transaction.person_category_id).category_id)
    @note = @transaction.note
  end

  # GET /money_transactions/new
  def new
    @people = current_user.people
    @transaction = MoneyTransaction.new
  end

  # GET /money_transactions/1/edit
  def edit; end

  # POST /money_transactions or /money_transactions.json
  def create
    @transaction = MoneyTransaction.new(transaction_params)
    create_note(@transaction, params)
    if @transaction.save
      flash[:notice] = 'Transaction was successfully created.'
      redirect_to person_path(@person)
    else
      render :new
    end
  end

  # PATCH/PUT /money_transactions/1 or /money_transactions/1.json
  def update
    if @transaction.update(transaction_params)
      flash[:notice] = 'Transaction was successfully updated.'
      redirect_to money_transaction_path(@transaction)
    else
      render :edit
    end
  end

  # DELETE /money_transactions/1 or /money_transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html do
        redirect_to person_path(@person), notice: 'Transaction was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # create note
  def create_note(transaction, params)
    return if params[:note_required].nil?

    note = Note.new(body: params[:note_body].values[0])
    transaction.note = note if note.valid?
    if note.valid?
      transaction.note = note
    else
      flash[:alert] = 'Note was not saved, maybe it was invalid'
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = MoneyTransaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:money_transaction).permit(:count, :person_category_id, :note_id, :important)
  end

  def set_person_category
    @person = current_user.people.find(@transaction.person_category.person_id)
  end

  def set_person_created_for
    @person = Person.find(PersonCategory.find(transaction_params[:person_category_id]).person_id)
  end
end

app/views/money_transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
    <% if transaction.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

        <ul>
          <% transaction.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group">
      <%= form.label :count %>
      <%= form.number_field :count, class:"form-control"%>
    </div>
  <br />
    <% if transaction.new_record?%>
      <div class="field form-group">
        <%= form.label 'Category'%>
        <%= form.select(:person_category_id, options_for_select(PersonCategory.where(person_id: @people).order(:person_id).map { |pc| [pc.select_title, pc.id]}), {}, {required: true, class: "form-control"}) %>
      </div>
      <br />
      <div class="field form-group">
        <%= form.label 'Note' %>
        <%= form.text_field :body, class: "form-control", placeholder: "write your text ..." %>
      </div>
    <% else %>
      <% unless transaction.note %>
          <div class="field form-group">
            <%=   form.label 'Note'   %>
            <%= form.text_field :body, class: "form-control" %>
          </div>
      <%   end %>
      <div class="field form-group">
        <%= form.hidden_field :person_category_id %>
      </div>
    <% end%>

  <br />
  <div class="field form-group">
    <%= form.label 'Is it important?'%>
    <%= form.select(:important, [ ['Yes', true], ['No', false]], {}, {required: true, class: "form-control"}) %>
  </div>

    <br />
    <div class="actions">
      <%= form.submit class:'btn btn-secondary' %>
    </div>
<% end %>

app/views/money_transactions/edit.html.erb
<br />
<div class="container">
  <h1>Editing Transaction</h1>
  <br/>
  <%= render 'form', transaction: @transaction %>
  <br/>
  <%= link_to 'Show', @transaction, class:"btn btn-secondary" %> |
  <%= link_to 'Delete', @transaction, class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %> |
  <%= link_to 'Back', money_transactions_path, class:"btn btn-dark" %>
</div>

app/views/money_transactions/index.html.erb
<br />
<div class="container">
  <h1>Transactions</h1>
  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Count</th>
        <th>Category</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @transactions.each do |transaction| %>
        <tr>
          <td><%= link_to transaction.count, transaction %></td>
          <td><%= transaction.person_category.category.title %></td>
          <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>

app/views/money_transactions/new.html.erb
<br/>
<div class="container">
  <h1>New Transaction</h1>
  <br/>
  <%= render 'form', transaction: @transaction %>
  <br/>
  <%= link_to 'Back', money_transactions_path, class:"btn btn-dark" %>
</div>

app/views/money_transactions/show.html.erb
<br />
<div class="container">
  <div class="jumbotron">
    <h1 class="display-4">
      <%= @transaction.person_category.person.first_name %>
      <%= @transaction.person_category.person.last_name %>
    </h1>

    <h5>
      <%= @transaction.person_category.category.title %>,
      <%= @transaction.count %> USD
      - <%= @transaction.person_category.category.transaction_type %>
    </h5>

    <p class="lead">
      Created: <%= @transaction.created_at %>
    </p>

    <% if @note %>
        <p class="card-text">Note: <%= @note.body%></p>
        <%= link_to "Edit note", edit_note_path(@note) %> |
        <%= link_to "Delete note", note_path(@note), method: :delete, data: { confirm: "Are you sure?" } %>
        <br />
    <% else %>
        No notes yet...
        <br />
    <%end%>

    <br/>
    <%= link_to 'Edit', edit_money_transaction_path(@transaction), class:"btn btn-secondary" %> |
    <%= link_to 'Delete', @transaction, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %> |
    <%= link_to 'Back', money_transactions_path, class:"btn btn-dark" %>
  </div>
</div>