config/routes.rb
Rails.application.routes.draw do
  resources :charts
  devise_for :users
  resources :categories
  resources :money_transactions
  resources :notes
  resources :people
  get "homepage", to: "home#homepage"
  root "people#index"
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :description, presence: true, length: { minimum: 3 }

  belongs_to :user
  has_many :person_categories, dependent: :destroy
  has_many :categories, through: :person_categories

  before_create :check_uniqueness
  before_destroy :check_people_count

  private

  def check_people_count
    throw(:abort) if user.people.count <= 1
  end

  def check_uniqueness
    throw(:abort) if user.people.exists?(description: description)
  end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  before_action :set_person, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found

  def render_not_found
    render 'public/404,html.erb'
  end

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
    @categories = @person.categories
    @person_categories = @person.person_categories.where(created_at: Time.zone.today.all_month)
  end

  # GET /people/new
  def new
    @person = current_user.people.build
  end

  # GET /people/1/edit
  def edit; end

  # POST /people or /people.json
  def create
    @person = current_user.people.build(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  def correct_user
    @person = current_user.people.find_by(id: params[:id])
    redirect_to people_path, notice: 'Not Authorized To Edit This Person' if @person.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def person_params
    params.fetch(:person, {})
    params.require(:person).permit(:first_name, :last_name, :description, :user_id)
  end
end

app/views/people/_categories.html.erb
<% if obj.any? %>
  <br />
  <div class="container">
    <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th>Transactions</th>
      <th>Total amount<th>
    </tr>
    </thead>

    <tbody>
    <% obj.each do |person_category|%>
      <tr>
        <td class="text-center">
          <div class="rounded-pill <%= person_category.category.transaction_type == true ? 'btn btn-success btn-lg' : 'btn btn-warning btn-lg' %>">
            <%= link_to person_category.category.title, category_path(person_category.category), class: "link-light"%>
          </div>
        </td>
        <td>
          <% if person_category.money_transactions.any? %>
            <ul class="list-group">
              <% person_category.money_transactions.order(important: :desc, created_at: :asc).each do |transaction|%>
                <% if transaction.important %>
                  <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-danger">
                <% else %>
                  <li class="list-group-item d-flex justify-content-between align-items-center">
                <% end %>
                <% if transaction.note%>
                  <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-success">
                <%end%>

                <div class="d-flex w-100 justify-content-between ">
                  <span class="badge bg-primary rounded-pill"><%= transaction.count  %></span>
                  <small><%= transaction.created_at.to_formatted_s(:short) %></small>
                </div>
                <div class="d-flex w-50 justify-content-around">
                  <%= link_to 'Update', edit_money_transaction_path(transaction), class:"btn btn-secondary btn-sm" %> |
                  <%= link_to 'Delete', money_transaction_path(transaction), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %>
                </div>
                </li>
              <%end%>
            </ul>
          <% else %>
            None
          <% end %>
        </td>
        <td class="text-center">
          <h3>
            <% if !person_category.category.transaction_type %>
              - <%= person_category.money_transactions.sum(&:count) %>
            <% else %>
              + <%= person_category.money_transactions.sum(&:count) %>
            <% end %>
          </h3>
        <td>
      </tr>
    <% end %>
    </tbody>
  </table>

    <div>
      <ul class="list-group">
        <li class="list-group-item list-group-item-danger"> important transaction</li>
        <li class="list-group-item list-group-item-success">transaction with note </li>
      </ul>
    </div>

  </div>

<% else %>
  <p> No categories yet ... <p>
<% end %>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <% form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>
  <br />
  <div class="field form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>
  <br />
  <div class="field form-group">
    <%= form.text_field :description, class:"form-control", placeholder:"Description" %>
  </div>
  <br />
  <div class="field form-group">
    <%= form.number_field :user_id, id: :person_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <br/>

  <div class="actions">
    <%= form.submit class:'btn btn-secondary'%>
  </div>
<% end %>

app/views/people/edit.html.erb
<br />
<div class="container">
  <h1>Editing Person</h1>
  <br/>
  <%= render 'form', person: @person %>
  <br/>
  <%= link_to 'Show', @person, class:"btn btn-secondary" %> |
  <%= link_to 'Delete', @person, class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %> |
  <%= link_to 'Back', people_path, class:"btn btn-dark" %>
</div>

app/views/people/index.html.erb
<% if user_signed_in? %>
  <br />
  <div class="container">
  <h1>People</h1>
  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @people.each do |person| %>
      <% if person.user == current_user %>
        <tr>
          <td><%= link_to person.first_name + ' ' + person.last_name, person %></td>
          <td><%= person.description %></td>
          <td><%= person.created_at %></td>
          <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Person', new_person_path, class:"btn btn-secondary" %>
</div>

<% else %>
  <div class="card bg-dark text-white text-center" style="height: 94vh; overflow: hidden;">
    <img src="https://www.polsov.com/upload/014/u1405/b/d/a86b4cd5.jpg" class="card-img" alt="index images">
    <div class="card-img-overlay">
      <h5 class="card-title">Welcome to the Best Finance Apps to Manage Bills and Debts!</h5>
      <p class="card-text">The main benefit of capital is not to make more money, but to make money for the sake of improving life.</p>
      <p class="card-text">For use it, sign in or sign up</p>
    </div>
  </div>
<% end %>

app/views/people/new.html.erb
<br/>
<div class="container">
  <h1>Add New Person</h1>
  <br/>
  <%= render 'form', person: @person %>
  <br />
  <%= link_to 'Back', people_path, class:"btn btn-dark" %>
</div>

app/views/people/show.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="display-4">
      <%= @person.first_name %>
      <%= @person.last_name %>
    </h1>
    <p class="lead">
      <%= @person.description %> |
      <%= @person.updated_at %>
    </p>
    <br/>
    <h2> Categories </h2>

    <%= render 'categories', obj: @person_categories %>

    <br />
    <%= link_to 'Edit', edit_person_path(@person), class:"btn btn-secondary" %> |

    <%= link_to 'Delete', @person, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %> |

    <%= link_to 'Back', people_path, class:"btn btn-dark" %>
  </div>
</div>