config/routes.rb
Rails.application.routes.draw do
  resources :charts
  devise_for :users
  resources :categories
  resources :money_transactions
  resources :notes
  resources :people
  get "homepage", to: "home#homepage"
  root "people#index"
end

app/views/pages/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-between" id="navbarTogglerDemo01">
    <%= link_to 'Exchequer App', homepage_path, class:"navbar-brand" %>

    <ul class="navbar-nav mr-auto mt-2 mt-lg-0 pull-xs-right align-items-right">

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Statistics", charts_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Transactions", money_transactions_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Categories", categories_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "All Users", people_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Add Person", new_person_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>

    </ul>
  </div>
  </div>
</nav>